### ISSUE TITLE
No user object passed to authZ plugin

### ISSUE THREAD

**Issue by ahmed-bacha** [twistlock/authz#19]
Hi, 

After compiling the project, connecting the plugin to docker daemon and trying the README policies, I saw in the logs that there was no `user object` processed by the plugin. This mean that no policy could be applied :( 

Any clues ? 

log : 
```
Jul 13 17:31:03 localhost authz-broker: {"allow":false,"err":"","fields.msg":"no policy applied (user: '' action: 'image_list')","level":"info","method":"GET","msg":"Request","time":"2016-07-13T17:31:03+02:00","uri":"/v1.22/images/json","user":""}
```

Thanks :)

**Comment by rmartinez3** [comment]
I updated to docker engine 1.12.0-rc4. After that, user object was being passed. Also you have to have certificates set up for the docker daemon and your client that is trying to use the docker daemon.

More information about that in this link: https://docs.docker.com/engine/security/https/

**Comment by ahmed-bacha** [comment]
Thanks @rmartinez3  :) , I have set up client/server certificates. 
Impatient to test it on the 1.12 release next week, I will keep you in touch : )

**Comment by ahmed-bacha** [comment]
Hi,

I have tested it with the 1.12-RC4, it worked like a charm :) , 

Thank you !
