### ISSUE TITLE
Publishing on Docker hub

### ISSUE THREAD

**Issue by yan-foto** [twistlock/authz#22]
Are there any plans to push the image on Docker hub? The only image listed on the hub is not pullable (i.e. empty)

**Comment by hekaldama** [comment]
Has this project been abandoned?

**Comment by liron-l** [comment]
Thanks @hekaldama @yan-foto you can pull the latest build using 
```
docker pull twistlock/authz-broker
```
I will make sure updates are automatically pushed to the hub.

**Comment by hekaldama** [comment]
Thanks!
