### ISSUE TITLE
Authz terminology mapping

### ISSUE THREAD

**Issue by chambm** [twistlock/authz#24]
Is there documentation for which authz terms map to which docker commands?

**Comment by liron-l** [comment]
@chambm the authorization subsystem defends the docker [remote API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/), the docker CLI calls this API when you invoke different commands so technically, the terminology is the same.
Note that most of the time this is a 1:1 mapping (e.g., docker version -> [version API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#show-the-docker-version-information))

**Comment by liron-l** [comment]
Closing this one.
