### ISSUE TITLE
Examples!

### ISSUE THREAD

**Issue by pgonyan** [twistlock/authz#27]
It would be interesting to write more examples about policies.

I want to create a policy that allow to run all users to 

1. pull and run any images *but* without volumes options, name, etc.
2. stop, rm images create by the users

**Comment by eranyanay** [comment]
Hi @pgonyan,
See the readme section about examples [here](https://github.com/twistlock/authz#examples)
If you find the existing examples lacking, please open an issue with specific more specific information
Closing for now
