### ISSUE TITLE
Document how this module relates to swarm mode

### ISSUE THREAD

**Issue by alexanderkjeldaas** [twistlock/authz#28]
How should the daemon be setup in a swarm?

Docker swarm / swarm mode is not mentioned in the documentation, which makes me believe that it doesn't work.  The documentation should specify how and if it works in docker swarm mode.

**Comment by stelcheck** [comment]
Is this accurate? I am researching authorization plugins right now, and if this is acurrate I would be curious to know if support is not available due to actual limitations or to simple current lack of implementation?

**Comment by liron-l** [comment]
Fixed by #65
