### ISSUE TITLE
twistlock/authz-broker policy failure

### ISSUE THREAD

**Issue by lvic4594** [twistlock/authz#40]
I am trying on Container Linux by CoreOS 1353.7.0 (Ladybug)
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Wed Apr 26 21:47:57 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Wed Apr 26 21:47:57 2017
 OS/Arch:      linux/amd64
From default account ("core") i've created user "user1" as a member of group docker:
sudo useradd -p "*" -U -m user1 -G docker
i added "readonly" policy for "user1" in /var/lib/authz-broker/policy.json
{"name":"policy_1","users":["user1"],"actions":["container"],"readonly":true}
and launched broker container:
docker run -d  --restart=always -v /var/lib/authz-broker/policy.json:/var/lib/authz-broker/policy.json -v /run/docker/plugins/:/run/docker/plugins twistlock/authz-broker
After I ssh into CoreOS system as "user1" I can do pretty much anything with docker, like pulling and removing docker images

**Comment by liron-l** [comment]
Hi @lvic4594, did you configure dockerd to use the authz plugin?
`--authorization-plugin list               Authorization plugins to load`
Also, consider installing the authz code as a v2 [authorization plugin](https://docs.docker.com/engine/extend/plugin_api/), this will require some changes in the code.

**Comment by lvic4594** [comment]
Got it for "user1": (Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'docker_info')). Using system default: https://index.docker.io/v1/
Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'image_create'). That looks like expected behavior.

Sorry, don't see anything about "v2 authorization plugin" in the link you've provided... Why should I consider doing that?
Thank you

**Comment by lvic4594** [comment]
I am trying to allow default user "core" to perform any docker operations:
policy.json:
{"name":"policy_1","users":["core"],"actions":["*"]}
{"name":"policy_2","users":["user1"],"actions":["container"],"readonly":true}

but when i run "docker ps" as "core" i have the following error:
Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'container_list')

**Comment by liron-l** [comment]
@lvic4594 currently only TLS authorization is supported so you need to configure docker with TLS certificate and provide a client certificate. See [instructions](https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl)

**Comment by lvic4594** [comment]
That would be proble

**Comment by lvic4594** [comment]
After I followed directions, I have the following error:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

systemctl list-units | grep docker
docker-tcp.socket                                                                        loaded active listening Docker Socket for the API                                           
docker.socket                                                                            loaded active listening Docker Socket for the API

**Comment by lvic4594** [comment]
I've configured dockerd and docker for TLS authorization using your link. It doesn't seem to help: on any policy like 
{"name":"policy_1","users":[""],"actions":[""]}
or 
{"name":"policy_1","users":["*"],"actions":["*"]}
I see the same error:
Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: 'client' action: 'container_list')

**Comment by liron-l** [comment]
You need to set the name of the user: client, and the action, in the allow list.

**Comment by lvic4594** [comment]
like: {"name":"policy_1","users":["client"],"actions":["*"]} in policy.json? 
What's the "allow list"? 
Sorry, I tried to use example from readme, don't have any other resource. Can i have some example?

**Comment by liron-l** [comment]
The action you want to apply, as written in the plugin log `container_list`. But ensure first that the plugin is actually loading the policy you specified and not another file.

**Comment by lvic4594** [comment]
You should see a log like loaded z policy. Should see it where?

**Comment by lvic4594** [comment]
More specifically: where's plugin log container_list? I don't see it with "find"

**Comment by liron-l** [comment]
The plugin logs when the policy is loaded, if you did not put it in the correct place, nothing will work.

**Comment by lvic4594** [comment]
According to "readme", the place is /var/lib/authz-broker/policy.json; that's where i put it...

**Comment by lvic4594** [comment]
I have created the file /var/lib/authz-broker/policy.json

**Comment by liron-l** [comment]
I suggest that you check inside the container that the policy is mounted and updated.

**Comment by lvic4594** [comment]
seems like chicken and egg problem: i start dockerd with --authorization-plugin=authz-broker : then I cannot "docker run" eg load plugin.  Is there default policy file?

**Comment by lvic4594** [comment]
i see "loaded" message when i start plugin:
time="2017-05-24T20:49:41Z" level=info msg="Loaded '1' policies"

**Comment by liron-l** [comment]
Hi, since I don't understand exactly what you did. I suggest you debug the plugin using the source code.
Specifically,

```
# From the root repository
$ make
# run the binary 
$ ./authz-broker --debug --policy-file /var/lib/authz-broker/policy.json
# This is the policy.json file
# {"name":"policy_1","users":["","*"],"actions":[""]}
# from **another** terminal stop docker and run it with the plugin
$ sudo service docker stop
$ sudo dockerd --authorization-plugin authz-broker
# from **another** terminal, check the plugin
 docker ps
```

**Comment by lvic4594** [comment]
Shouldn't i also run "authz-broker" as root?
Shouldn't i also set env vars from dockerfile, like AUTHORIZER=basic?
Anyway, here's the output from "authz-broker":
INFO[0128] Loaded '1' policies                          
DEBU[0145] Received AuthZ request, method: 'GET', url: '/v1.24/containers/json' 
DEBU[0145] no policy applied (user: 'client' action: 'container_list') 
{"allow":false,"err":"","fields.msg":"no policy applied (user: 'client' action: 'container_list')","level":"info","method":"GET","msg":"Request","time":"2017-05-25T14:33:02Z","uri":"/v1.24/containers/json","user":"client"}
And "docker ps" results in 
Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: 'client' action: 'container_list')
So, it looks as policy is loaded but not parsed.

**Comment by lvic4594** [comment]
Does selinux=enabled makes any difference? 
here's my dockerd line:
**dockerd --authorization-plugin=authz-broker --tlsverify --tlscacert=/home/core/ca.pem --tlscert=/home/core/server-cert.pem --tlskey=/home/core/server-key.pem -H=0.0.0.0:2378 --insecure-registry=0.0.0.0/0 --selinux-enabled**

**Comment by liron-l** [comment]
it looks like something is wrong with your policy. I suggest you add prints in the code and debug it.
You need to have
```
{"name":"policy_1","users":["client"],"actions":[""]}
```
or
```
{"name":"policy_1","users":["client"],"actions":["container_list"]}
```

**Comment by lvic4594** [comment]
{"name":"policy_1","users":["client"],"actions":["*"]} - this works. It looks as something is wrong not with my policy but with your matching in AuthZReq: 
for _, user := range policy.Users {
			if user == authZReq.User {
...
eg regexp is not used to match user vs. policy user
Where's"client" in AuthZReq coming from?

**Comment by liron-l** [comment]
In authorization, you can't match a user name against regular expression only against the full name (otherwise, people might impersonate you).
client is the CN (common name) in the certificate you generated. This is propagated via docker not authz.

I'm going to close the issue, since it appears there is no problem with the code. As said, feel free to contribute with pull requests to improve the documentation or code.

**Comment by lvic4594** [comment]
The policy examples in "readme" could certainly be improved from this experience

**Comment by liron-l** [comment]
Thanks, feel free to contribute a pull request.

**Comment by lvic4594** [comment]
Thanks for your help. One more question: suppose i want authorization policies per shell users, not certificates. Can this plugin work without ssl certificates?

**Comment by lvic4594** [comment]
If TLS is enabled, the default user authorization flow extracts the user
details from the certificate subject name. That is, the User field is set
to the client certificate subject common name, and the AuthenticationMethod
field is set to TLS.
Is there a way to customize authorization method? Suppose I need to extract
user details from LDAP...
Thanks

**Comment by liron-l** [comment]
Hi @lvic4594, no.
The docker daemon only supports TLS authentication. 
[twistlock](www.twistlock.com) offers local (unix) and LDAP authentication in our dev/enterprise edition.

**Comment by lvic4594** [comment]
Thanks Liron,
Would it be possible to change response of dockerd if operation is
permitted? For example in the case of "docker image" to see only images
from the certain repos?

**Comment by liron-l** [comment]
No, this scenario is not supported. I suggest you read [docker documenation](https://docs.docker.com/engine/extend/plugins_authorization/).

**Comment by lvic4594** [comment]
That doesn't exactly tell me what i can/ cannot do with plugins... My goal
is "container isolation": the user should only be able to see and use
images in the repo assigned to that user. For example: user "core" should
only be able to see and use images like <registry>/core/busybox:latest but
not <registry>/platform/busybox:latest; Would it be possible to implement
with plugins?
Thanks again,

**Comment by liron-l** [comment]
No.
