### ISSUE TITLE
Godeps is not found on branch master

### ISSUE THREAD

**Issue by deathmemory** [twistlock/authz#41]
Godeps is not found on branch master. And tag 0.1 tips
"Package (golang.org/x/sys/unix) not found"
I can't build it , please help, thks!

**Comment by liron-l** [comment]
@deathmemory we don't use Godep, we have all dependencies under .vendor version. Please update your go framework.

**Comment by deathmemory** [comment]
thanks for your respone !
I use these commands to build authz
```
 $ cd broker/
 $ go build
 $ mv broker ../authz-broker 
 $ cd ..
 $ docker build .
```
I think the the readme description about build & usage should be update.
Best wishes
