### ISSUE TITLE
user name always comes empty on docker 1.10

### ISSUE THREAD

**Issue by lvic4594** [twistlock/authz#43]
See this only on CoreOS 1122.3.0/docker 1.10.3: user name in authz callback always comes empty regardless of /CN in client certificate. Works as described on CoreOS 1409.7.0/ docker 1.12.6
Not plugin issue obviously, but i didn't see docker version requirements in "readme"...

**Comment by liron-l** [comment]
@lvic4594 passing the CN was only introduce in later docker versions (but the code still works), feel free to send a PR to update the readme.

**Comment by lvic4594** [comment]
Any idea in what version of docker has that feature (passing CN) been introduced? 
Thank you,

**Comment by liron-l** [comment]
https://github.com/moby/moby/releases?after=v1.12.6
1.13-rc5

**Comment by caoruidong** [comment]
On old version of docker, code works but can't tell the user. So passing CN is need if I want to use RBAC?
