### ISSUE TITLE
corporate LDAP integration?

### ISSUE THREAD

**Issue by 1605200517** [twistlock/authz#44]
I am new to this, so my question might be stupid. :-)

Nevertheless - is this plugin the right place to integrate with corporate LDAP groups to layout who can create/run containers, down to specific stacks?

**Comment by liron-l** [comment]
Hello @1605200517, you can extend the framework given here as a baseline to support LDAP auth, or use our official [enterprise offering](https://www.twistlock.com/) (which support LDAP auth out of the box). Thanks

**Comment by thiagoalves** [comment]
@liron-l Can I use the enterprise offering to setup LDAP authN for the docker API socket?

I would like to avoid using server/client keys as described on https://docs.docker.com/engine/security/https/

**Comment by liron-l** [comment]
@thiagoalves possibly, you can contact the twistlock team using the website.
