### ISSUE TITLE
Ability to Block Command Options

### ISSUE THREAD

**Issue by eets8305** [twistlock/authz#47]
Looking for the ability to block specific command options.  For example, I want users to be able to create containers using ‘docker run’ but block users from applying the --privileged option.  It does not appear that this capability exists.  Looks like all or nothing.  Can this please be confirmed one way or the other?

**Comment by liron-l** [comment]
Hi @eets8305, authorization plugins uses the docker [REST API](https://docs.docker.com/engine/api/v1.24/), which the docker client also uses. 
This is fully supported by the plugin, see sample [policy](https://github.com/twistlock/authz/blob/master/authz/policy.json).

**Comment by eets8305** [comment]
Thank you for the information.  I did take a closer look at this and examined the log information and when I apply the --privileged option there is nothing presented by the logs which would help be understand how to craft an appropriate policy to block this option.  Additionally, I have examined the various policy examples but fail to understand how a policy can be crafted to block command options (i.e. allow run but block --privileged). Could you offer some additional details as to how this may be accomplished?

**Comment by liron-l** [comment]
@eets8305, this plugin only show examples how to blocks the methods in the REST API, if you want to manipulate the body of a request, you need to write your own plugin code, you can use the code in this repository as baseline, or the sample API plugin code [by docker](https://github.com/docker/go-plugins-helpers/tree/master/authorization). 
As said, docker commands can be mapped to multiple APIs (and the mapping is not 1:1 and changes between docker version), so we only offer support for the REST API.
If you want to better understand this mapping, I suggest that you inspect the log of the plugin when you run it in verbose mode.

Our commercial [product](https://www.twistlock.com/) offer all this and more, but if this is for personal usage, I suggest you fork the code or use the sample code I provided in the link,  

I'm going to close this issue for now.
