### ISSUE TITLE
Anyone successfully using this plugin ???

### ISSUE THREAD

**Issue by JTG2020** [twistlock/authz#53]
I don't see any work is being done on this plugin and if it is being supported. Anyone successfully used this plugin yet??
issue - I have docker version 18.06.1-ce. I followed all the 3 steps mentioned for "Running inside container". Downloaded and ran image successfully however policy.json under /var/lib/authz-broker/ is getting created as directory and not file. Same thing with /var/log/authz.log file. authz.log is getting created as directory. The major problem, when I  applied --authorization-plugin=authz-broker flag, the daemon is unable to start because authz-broker doesn't exist in /var/run/docker/plugins.

**Docker daemon output** 
INFO[2018-10-18T08:00:57.112840870-04:00] Docker daemon                                 commit=e68fc7a graphdriver(s)=overlay2 version=18.06.1-ce
WARN[2018-10-18T08:00:57.113232274-04:00] Unable to locate plugin: authz-broker, retrying in 1s 
WARN[2018-10-18T08:00:58.114458823-04:00] Unable to locate plugin: authz-broker, retrying in 2s 
WARN[2018-10-18T08:01:0.115289904-04:00] Unable to locate plugin: authz-broker, retrying in 4s 
WARN[2018-10-18T08:01:04.116593397-04:00] Unable to locate plugin: authz-broker, retrying in 8s 
Error validating authorization plugin: plugin "authz-broker" not found
---
Are the instructions accurate ? Why files are getting created as directories. Am i missing something ?

**Comment by liron-l** [comment]
@JTG2020 I've just tested it, and everything works on docker 18.06.

Suggest you start with the following instructions:
```bash
make
cp authz/policy.json /var/lib/authz-broker/policy.json
./bin/authz-broker 
```
If you want to run as container, you need to first copy the policy file to the target directory (otherwise docker thinks he need to generate it as a file)

**Comment by JTG2020** [comment]
@liron-l  Thank you for your time. Are you saying i should compile the code first ?

**Comment by liron-l** [comment]
No (except go).

**Comment by liron-l** [comment]
Closing.

**Comment by doctorCC** [comment]
I am running into the same issue I believe.  I ran the 
make all [which seemed to work and generate some Docker image]
cp authz/policy.json /var/lib/authz-broker/policy.json [as highlighted above]
./bin/authz-broker  [fails with ]

_./bin/authz-broker
**panic: read /var/lib/authz-broker/policy.json: is a directory**

goroutine 1 [running]:
main.main.func1(0xc0000e2280)
	/home/ccramer/go/src/github.com/twistlock/authz/broker/main.go:63 +0x337
github.com/twistlock/authz/vendor/github.com/codegangsta/cli.HandleAction(0x76e8c0, 0x8142d8, 0xc0000e2280, 0xc000066300, 0x0)
	/home/ccramer/go/src/github.com/twistlock/authz/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/twistlock/authz/vendor/github.com/codegangsta/cli.(*App).Run(0xc0000809c0, 0xc00000e1b0, 0x1, 0x1, 0x0, 0x0)
	/home/ccramer/go/src/github.com/twistlock/authz/vendor/github.com/codegangsta/cli/app.go:259 +0x600
main.main()
	/home/ccramer/go/src/github.com/twistlock/authz/broker/main.go:102 +0x4da
_

When I try to start a container with
 **docker run -d  --restart=always -v /var/lib/authz-broker/policy.json:/var/lib/authz-broker/policy.json -v /run/docker/plugins/:/run/docker/plugins twistlock/authz-broker**
I keep see the failures inside the Container log
_main.main()
	/home/liron/src/github.com/twistlock/authz/broker/main.go:100 +0x4ce
panic: read /var/lib/authz-broker/policy.json: is a directory

goroutine 1 [running]:
panic(0x71ce60, 0xc42006b170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main.func1(0xc4200d20f0)
	/home/liron/src/github.com/twistlock/authz/broker/main.go:61 +0x396
vendor/github.com/codegangsta/cli.(*App).Run(0xc4200d0300, 0xc42000a250, 0x1, 0x1, 0x0, 0x0)
	/home/liron/src/vendor/github.com/codegangsta/cli/app.go:164 +0x69f
main.main()
	/home/liron/src/github.com/twistlock/authz/broker/main.go:100 +0x4ce
panic: read /var/lib/authz-broker/policy.json: is a directory_

Am I missing something, is there another instruction page with how to set this up?

**Comment by liron-l** [comment]
@doctorCC 
I don't think modifying the policy while the container is running is supported (but feel free to add an inotify patch if this is what you want). Suggest you just restart the container.
