### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by alobaidan** [twistlock/authz#54]
Could you tell me how install this plugin in the host please ?
Because I don’t understand what does wget xxx means. I need full command instead of xxx please.

Many thanks 
Ibrahim

**Comment by liron-l** [comment]
Hi @alobaidan you need to compile the project using `make` and then run `install.sh`.

**Comment by alobaidan** [comment]
Hi, I know that need to compile the project using make but I do not understand that what does xxx means.

therefore could you tell me the full command wget (xxx) ?
many thanks
Ibrahim
