### ISSUE TITLE
different users

### ISSUE THREAD

**Issue by alobaidan** [twistlock/authz#56]
I would like  to create different users as roles in RBAC. For example, user1 can access container1  while user2 in docker groups like Bob cannot access container1.

as I know Docker daemon only see network requests sent from sockets and no username on the request.

therefore, Is twistlock provide that technique or not ?

Many thanks
Ibrahim

**Comment by liron-l** [comment]
This is not relevant to this plugin. The docker auth subsystem only works with certificates. You can read more about it in the official docker GitHub repo
https://docs.docker.com/engine/extend/plugins_authorization/
