### ISSUE TITLE
cp authz/policy.json /var/lib/authz-broker/policy.json cp: cannot create regular file '/var/lib/authz-broker/policy.json': No such file or directory

### ISSUE THREAD

**Issue by alobaidan** [twistlock/authz#61]
Hi I could not copy authz/policy.json to /var/lib/authz-broker/policy.json': 
i got this error 
/var/lib/authz-broker/policy.json':  No such file or directory

but i could copy the file authz/policy.json to /usr/lib/docker/policy.json'

so how i can run it please or how i can solve this problem ?

thansk you

**Comment by liron-l** [comment]
@alobaidan i don't know what you referring to or what command you are running.
If you run cp, you need to mkdir the folder first.

If you open a bug, please first explain what step are you trying to do, and what exactly did not work.

**Comment by alobaidan** [comment]
thank you for your response, please see the picture 
![image](https://user-images.githubusercontent.com/14161637/55027374-0cb4b380-4ffd-11e9-9267-f3dfe84f8d63.png)

**Comment by liron-l** [comment]
@alobaidan in linux, you can't copy a file to a non-existing directory.
You need to run mkdir -p xxx 
https://linux.die.net/man/2/mkdir

**Comment by alobaidan** [comment]
thank you very much
