### ISSUE TITLE
./bin/authz-broker 

### ISSUE THREAD

**Issue by alobaidan** [twistlock/authz#62]
hi When i run the plugin through ./bin/authz-broker 

i got error 
![image](https://user-images.githubusercontent.com/14161637/55029190-5d2e1000-5001-11e9-9f82-169e6c011720.png)

I have copied the policy file. what is the next step after copy the policy file ?

many thansk

**Comment by liron-l** [comment]
@alobaidan 
Only Linux is supported and tested and there are instructions in the readme folder.

If you don't have permissions, run as root.

Please avoid opening additional issues unless you work with supported scenarios.
