### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by funkytaco** [twistlock/authz#7]
I'd like to see some documentation for this.

I'm curious where do I set things like this:

{"name":"policy_1","users":["alice"],"actions":["*"]}

Also, here's my Docker daemon ExecStart:

> ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --cluster-store consul://0.0.0.0:8500 --label node=server1 --exec-opt native.cgroupdriver=cgroupfs

**Comment by liron-l** [comment]
Thanks @funkytaco , you can read how to specify the policy when running the authorization plugin in a [container](https://github.com/twistlock/authz#running-inside-a-container). Without a container you place the policy file under /var/lib/authz-broker/policy.json.

Note that:
1. You must start the daemon with the ```--authz-plugin=authz-broker``` set.
2. User authentication is still work in progress in the daemon.

**Comment by eranyanay** [comment]
Documentation is updated.
Closing
