### ISSUE TITLE
Override response from daemon

### ISSUE THREAD

**Issue by ungureanuvladvictor** [twistlock/authz#8]
Do you have any example code on how to filter the response from the daemon to the client ? For example docker ps should not show the same content for all the users.

**Comment by liron-l** [comment]
Thanks @ungureanuvladvictor, currently there is no way to modify the docker response, only block and inspect.

Having said that, you can just create group policies of 'who can do what'. That is, even if a user can see a container via ```ps```, he can't interact with it (similar to directory services).
