### ISSUE TITLE
Error building the plugin

### ISSUE THREAD

**Issue by smakam** [twistlock/authz#9]
hi 
I was trying to follow these instructions to build plugin:
Install go 1.5 and docker.
Install godep.
Clone the project.
Restore go dependencies:
  $ godep restore
Build the binary and image:
  $ make all

I get following error in "make all" step:
CGO_ENABLED=0 go build  -o authz-broker -a -installsuffix cgo ./broker/main.go
broker/main.go:8:2: cannot find package "github.com/twistlock/authz/authz" in any of:
	/usr/local/go/src/github.com/twistlock/authz/authz (from $GOROOT)
	/home/sreeni/authz/src/github.com/twistlock/authz/authz (from $GOPATH)
broker/main.go:9:2: cannot find package "github.com/twistlock/authz/core" in any of:
	/usr/local/go/src/github.com/twistlock/authz/core (from $GOROOT)
	/home/sreeni/authz/src/github.com/twistlock/authz/core (from $GOPATH)
make: *** [binary] Error 1

Any ideas?
I dont see "twistlock" directory under github.com.

thanks
Sreenivas

**Comment by zozo123** [comment]
Dear Sreenivas,

Your go environment isn't properly set. Please follow all the instructions
at https://golang.org/doc/install#install

Thank you for trying AuthZ,

Yossi

**Comment by smakam** [comment]
hi Yossi
Thanks for the quick response.

I was able to try out the GO sample programs as specified in https://golang.org/doc/code.html with no issues. I have GO 1.5 installed. 
I tried 2 options:
cloning the authz project into my go workspace directory which was specified as GOPATH. 
cloning the authz project into a directory and making that as GOPATH.

In both cases, I hit same issue as mentioned below.

1 question:
In Godeps.json, I dont see twistlock mentioned. is that expected? I am new to GO, its possible that I am missing something basic. 

When I did "godep restore" before "make all", I got this error:
godep: Dep (github.com/docker/go-connections/tlsconfig) restored, but was unable to load it with error:
	Package (golang.org/x/sys/unix) not found
godep: Error checking some deps.
- it did seem to complete except the error above.

Thanks
Sreenivas

**Comment by smakam** [comment]
sorry, I meant to say, In both options, I hit same issue in "make all":
CGO_ENABLED=0 go build -o authz-broker -a -installsuffix cgo ./broker/main.go
broker/main.go:8:2: cannot find package "github.com/twistlock/authz/authz" in any of:
/usr/local/go/src/github.com/twistlock/authz/authz (from $GOROOT)
/home/sreeni/authz/src/github.com/twistlock/authz/authz (from $GOPATH)
broker/main.go:9:2: cannot find package "github.com/twistlock/authz/core" in any of:
/usr/local/go/src/github.com/twistlock/authz/core (from $GOROOT)
/home/sreeni/authz/src/github.com/twistlock/authz/core (from $GOPATH)
make: *** [binary] Error 1

thanks
Sreenivas

**Comment by liron-l** [comment]
@smakam you need to either ```go get xxxx``` the project or clone it from this path:/usr/local/go/src/github.com/twistlock

**Comment by smakam** [comment]
@liron-l 
Thanks for your response. It fixed my issue with "go get" and I was able to successfully build twistlock/authz-broker container. 

I tried to start the plugin and daemon like below:
docker run -d  --restart=always -v /var/lib/authz-broker/policy.json:/var/lib/authz-broker/policy.json -v /run/docker/plugins/:/run/docker/plugins twistlock/authz-broker
sudo docker daemon --authorization-plugin=authz-broker  &

I created this policy in /var/lib/authz-broker/policy.json. Initially, "policy.json" was a directory and authz plugin complained about it. I create this file "policy.json" in /var/lib/authz-broker with content below.
{"name":"policy_1","users":["sreeni"],"actions":["*"]}

I get this error, looks like its not able to find policy.
$ docker ps
ERRO[0312] AuthZRequest for GET /v1.22/containers/json returned error: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'container_list') 
ERRO[0312] Handler for GET /v1.22/containers/json returned error: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'container_list') 
Error response from daemon: authorization denied by plugin authz-broker: no policy applied (user: '' action: 'container_list')

Not clear if I am missing something else here:

1 question below, this could be related to my issue:
Does authz plugin and docker daemon run in same node? Since authz plugin is itself started as docker container, not clear how it works. If they can run in different node, how do we specify where the plugin runs?

Thanks
Sreenivas

**Comment by liron-l** [comment]
Hi @smakam, plugins must run on the same node as the docker daemon. This is docker plugin design.

Re authorization, currently all rules must have empty user (since you docker currently doesn't know to identify user).
This support is coming in docker 1.11.

**Comment by smakam** [comment]
Hi @liron-l 
Thanks again, with empty user, policy works fine. 

1 thing that i found weird:
to get a read-only container policy working, I first started docker daemon with authorization plugin, started authz plugin container and then restarted docker daemon with authorization plugin enabled. Since authz docker container had restart enabled, that authz container got started and then the read-only container policy worked fine. 
I kind of found it weird to have a container policy being  controlled by another container.. I guess with multi-user support, this authz plugin container will be started by privileged user?

Thanks
Sreenivas

**Comment by liron-l** [comment]
authz should be used when you run the daemon via HTTP/S. 
If you can access the docker socket, it means you are root and essentially can do whatever you want (and among other things, just remove the authz flag).
That is, flow should be:
1. Admin configure the system with auhz (via service or container)
2. Admin opens docker HTTP/S ports.
3. External users are authenticated and authorized.

**Comment by smakam** [comment]
ok, thanks @liron-l 
I will go ahead and close the issue.

Sreenivas

**Comment by bukharyi** [comment]
Hi @liron-l 

When you mentioned that currently all rules must have empty user, then we can only have 1 POLICY for the time being right?. 

"Re authorization, currently all rules must have empty user (since you docker currently doesn't know to identify user). This support is coming in docker 1.11."


For these example currently it is not valid..

Alice can run all Docker commands: {"name":"policy_1","users":["alice"],"actions":["*"]}
All users can run all Docker commands: {"name":"policy_2","users":["*"],"actions":["*"]}
Alice and Bob can create new containers: {"name":"policy_3","users":["alice","bob"],"actions":["container_create"]}

**Comment by alobaidan** [comment]
Hi
I have the same question, I am using debian OS. I installed go1.10.2 and godep tooles.

how I can clone the project because i got error when I write gith clone https://github.com/twistlock/authz

so could you help me please?

**Comment by liron-l** [comment]
@alobaidan git issues are not in the scope of this project; suggest you check stackoverflow

**Comment by alobaidan** [comment]
thank you for your response. so could you please provide the full command for go get xxxx to install twistlock

**Comment by liron-l** [comment]
All commands to build the project are described in the wiki.
